### Section 4.1: Exercise on Functions

In [11]:
def convert_units():
    print('Choose conversion type:\n1. Length (m <-> ft)\n2. Weight (kg <-> lbs)\n3. Volume (L <-> gal)')
    choice = input('Enter 1, 2, or 3: ')
    try:
        val = float(input('Enter the value to convert: '))
        if choice == '1':
            direction = input('Enter A for m to ft, B for ft to m: ').upper()
            result = val * 3.28084 if direction == 'A' else val / 3.28084
            print(f'Result: {result} ft' if direction == 'A' else f'Result: {result} m')
        elif choice == '2':
            direction = input('Enter A for kg to lbs, B for lbs to kg: ').upper()
            result = val * 2.20462 if direction == 'A' else val / 2.20462
            print(f'Result: {result} lbs' if direction == 'A' else f'Result: {result} kg')
        elif choice == '3':
            direction = input('Enter A for L to gal, B for gal to L: ').upper()
            result = val * 0.264172 if direction == 'A' else val / 0.264172
            print(f'Result: {result} gal' if direction == 'A' else f'Result: {result} L')
        else:
            print('Invalid conversion type.')
            return None
        return result
    except ValueError:
        print('Error: Invalid input. Please enter numeric values.')
        return None

def list_operations():
    print('Choose operation:\n1. Sum\n2. Average\n3. Maximum\n4. Minimum')
    choice = input('Enter 1, 2, 3, or 4: ')
    try:
        nums_str = input('Enter numbers separated by spaces: ')
        nums = [float(x) for x in nums_str.split()]
        if not nums:
            raise ValueError('List cannot be empty.')
        if choice == '1':
            res = sum(nums)
        elif choice == '2':
            res = sum(nums) / len(nums)
        elif choice == '3':
            res = max(nums)
        elif choice == '4':
            res = min(nums)
        else:
            print('Invalid operation choice.')
            return None
        print(f'Result: {res}')
        return res
    except ValueError as e:
        print(f'Error: {e}. Please ensure you enter valid numeric values.')
        return None
        # This will actually run the functions
convert_units()
list_operations()

Choose conversion type:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Enter 1, 2, or 3: 3
Enter the value to convert: 1000
Enter A for L to gal, B for gal to L: B
Result: 3785.412534257983 L
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 3
Enter numbers separated by spaces: 2
Result: 2.0


2.0

### Section 4.2: Exercise on List Manipulation

In [2]:
def extract_every_other(lst):
    return lst[::2]

def get_sublist(lst, start, end):
    return lst[start:end+1]

def reverse_list(lst):
    return lst[::-1]

def remove_first_last(lst):
    return lst[1:-1]

def get_first_n(lst, n):
    return lst[:n]

def get_last_n(lst, n):
    return lst[-n:]

def reverse_skip(lst):
    return lst[-2::-2]

# Testing the functions
test_list = [1, 2, 3, 4, 5, 6]
print('1. Extract every other:', extract_every_other(test_list))
print('2. Sublist (2 to 4):', get_sublist(test_list, 2, 4))
print('3. Reverse:', reverse_list(test_list))
print('4. Remove first and last:', remove_first_last(test_list))
print('5. First 3 elements:', get_first_n(test_list, 3))
print('6. Last 2 elements:', get_last_n(test_list, 2))
print('7. Reverse skip:', reverse_skip(test_list))

1. Extract every other: [1, 3, 5]
2. Sublist (2 to 4): [3, 4, 5]
3. Reverse: [6, 5, 4, 3, 2, 1]
4. Remove first and last: [2, 3, 4, 5]
5. First 3 elements: [1, 2, 3]
6. Last 2 elements: [5, 6]
7. Reverse skip: [5, 3, 1]


### Section 4.3: Exercise on Nested List

In [12]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    return sum(deep_flatten(lst))

def remove_element(lst, elem):
    modified_list = []
    for item in lst:
        if isinstance(item, list):
            modified_list.append(remove_element(item, elem))
        elif item != elem:
            modified_list.append(item)
    return modified_list

def find_max(lst):
    return max(deep_flatten(lst))

def count_occurrences(lst, elem):
    return deep_flatten(lst).count(elem)

def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat) if flat else 0

flatten = deep_flatten
# 1. Flatten a Nested List
test_list_1 = [[1, 2], [3, 4], [5]]
print("1. Flatten:", flatten(test_list_1))

# 2. Accessing Nested List Elements
test_list_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("2. Access Element [1, 2]:", access_nested_element(test_list_2, [1, 2]))

# 3. Sum of All Elements
test_list_3 = [[1, 2], [3, [4, 5]], 6]
print("3. Sum Nested:", sum_nested(test_list_3))

# 4. Remove Specific Element
test_list_4 = [[1, 2], [3, 2], [4, 5]]
print("4. Remove '2':", remove_element(test_list_4, 2))

# 5. Find the Maximum Element
print("5. Find Max:", find_max(test_list_3))

# 6. Count Occurrences
test_list_6 = [[1, 2], [2, 3], [2, 4]]
print("6. Count '2's:", count_occurrences(test_list_6, 2))

# 7. Flatten a List of Lists of Lists
test_list_7 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print("7. Deep Flatten:", deep_flatten(test_list_7))

# 8. Nested List Average
test_list_8 = [[1, 2], [3, 4], [5, 6]]
print("8. Average:", average_nested(test_list_8))

1. Flatten: [1, 2, 3, 4, 5]
2. Access Element [1, 2]: 6
3. Sum Nested: 21
4. Remove '2': [[1], [3], [4, 5]]
5. Find Max: 6
6. Count '2's: 3
7. Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average: 3.5


### Section 10.1: Basic Vector and Matrix Operation with Numpy

In [13]:
import numpy as np

# Problem 1
empty_arr = np.empty((2, 2))
ones_arr = np.ones((4, 2))
fill_arr = np.full((3, 3), 7)
zeros_like_arr = np.zeros_like(fill_arr)
ones_like_arr = np.ones_like(fill_arr)
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)

# Problem 2
range_arr = np.arange(10, 50)
matrix_3x3 = np.arange(9).reshape(3, 3)
identity_3x3 = np.eye(3)
random_30 = np.random.random(30)
mean_30 = random_30.mean()
random_10x10 = np.random.random((10, 10))
min_val, max_val = random_10x10.min(), random_10x10.max()

zero_10 = np.zeros(10)
zero_10[4] = 1

arr_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr_to_reverse[::-1]

border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0

checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("--- Problem 1 ---")
print("1. Empty Array (2x2):\n", empty_arr)
print("\n2. Ones Array (4x2):\n", ones_arr)
print("\n3. Filled Array (3x3 with 7s):\n", fill_arr)
print("\n4. Zeros Like Array:\n", zeros_like_arr)
print("\n5. Ones Like Array:\n", ones_like_arr)
print("\n6. Array from List:\n", arr_from_list)

print("\n--- Problem 2 ---")
print("1. Range Array (10 to 49):\n", range_arr)
print("\n2. 3x3 Matrix (0 to 8):\n", matrix_3x3)
print("\n3. 3x3 Identity Matrix:\n", identity_3x3)
print(f"\n4. Mean of Random 30 Array: {mean_30}")
print(f"\n5. 10x10 Random Array - Min: {min_val}, Max: {max_val}")
print("\n6. Zero Array with 5th element as 1:\n", zero_10)
print("\n7. Reversed Array:\n", reversed_arr)
print("\n8. 2D Array with 1 on border and 0 inside:\n", border_arr)
print("\n9. Checkerboard Pattern:\n", checkerboard)

--- Problem 1 ---
1. Empty Array (2x2):
 [[23. 51.]
 [13. 29.]]

2. Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Filled Array (3x3 with 7s):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Like Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones Like Array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

6. Array from List:
 [1 2 3 4]

--- Problem 2 ---
1. Range Array (10 to 49):
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of Random 30 Array: 0.4596732236753659

5. 10x10 Random Array - Min: 0.0002605358161225091, Max: 0.9877325563882651

6. Zero Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed Array:
 [0 4 0 0 2 1]

8. 2D Array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard Pattern:
 [

In [14]:
# Problem 3
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition = x + y
subtraction = x - y
multiplication = x * 10
squared = np.square(x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.column_stack((v, w))

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print('Error:', e)
    print('Explanation: x is a 2D array of shape (2,2) and v is a 1D array of shape (2,). np.concatenate requires arrays to have the same number of dimensions.')
    print("--- Problem 3 ---")
print("1. Addition (x + y):\n", addition)
print("\n2. Subtraction (x - y):\n", subtraction)
print("\n3. Multiplication (x * 10):\n", multiplication)
print("\n4. Squared (x^2):\n", squared)
print(f"\n5. Dot Product (v.w): {dot_vw}")
print(f"   Dot Product (x.v): {dot_xv}")
print("   Dot Product (x.y):\n", dot_xy)
print("\n6. Concatenate x & y along row:\n", concat_xy_row)
print("\n   Concatenate v & w along column:\n", concat_vw_col)
print("\n7. Error Handling Output (x & v concatenation):")
# (Your try-except block will print the answer for #7 right below this!)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2D array of shape (2,2) and v is a 1D array of shape (2,). np.concatenate requires arrays to have the same number of dimensions.
--- Problem 3 ---
1. Addition (x + y):
 [[ 6  8]
 [10 13]]

2. Subtraction (x - y):
 [[-4 -4]
 [-4 -3]]

3. Multiplication (x * 10):
 [[10 20]
 [30 50]]

4. Squared (x^2):
 [[ 1  4]
 [ 9 25]]

5. Dot Product (v.w): 219
   Dot Product (x.v): [29 77]
   Dot Product (x.y):
 [[19 22]
 [50 58]]

6. Concatenate x & y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

   Concatenate v & w along column:
 [[ 9 11]
 [10 12]]

7. Error Handling Output (x & v concatenation):


In [6]:
# Problem 4
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print('1. A * A^-1 == I:', np.allclose(identity_check, np.eye(2)))

AB = np.dot(A, B)
BA = np.dot(B, A)
print('2. AB != BA:', not np.allclose(AB, BA))

AB_T = AB.T
B_T_A_T = np.dot(B.T, A.T)
print('3. (AB)^T == B^T * A^T:', np.allclose(AB_T, B_T_A_T))

coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])
constants = np.array([-1, -3, 9])

coeff_inv = np.linalg.inv(coeff_matrix)
solution_inv = np.dot(coeff_inv, constants)
print('Solution via Inverse Method (x, y, z):', solution_inv)

solution_solve = np.linalg.solve(coeff_matrix, constants)
print('Solution via np.linalg.solve (x, y, z):', solution_solve)

1. A * A^-1 == I: True
2. AB != BA: True
3. (AB)^T == B^T * A^T: True
Solution via Inverse Method (x, y, z): [ 2.  1. -2.]
Solution via np.linalg.solve (x, y, z): [ 2.  1. -2.]


### Section 10.2: Experiment: How Fast is Numpy?

In [7]:
import time
import random

size = 1_000_000
list1 = [random.random() for _ in range(size)]
list2 = [random.random() for _ in range(size)]
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
res_list_add = [list1[i] + list2[i] for i in range(size)]
time_list_add = time.time() - start

start = time.time()
res_arr_add = arr1 + arr2
time_arr_add = time.time() - start
print(f'Addition -> List: {time_list_add:.5f}s, NumPy: {time_arr_add:.5f}s')

start = time.time()
res_list_mul = [list1[i] * list2[i] for i in range(size)]
time_list_mul = time.time() - start

start = time.time()
res_arr_mul = arr1 * arr2
time_arr_mul = time.time() - start
print(f'Multiplication -> List: {time_list_mul:.5f}s, NumPy: {time_arr_mul:.5f}s')

start = time.time()
res_list_dot = sum(list1[i] * list2[i] for i in range(size))
time_list_dot = time.time() - start

start = time.time()
res_arr_dot = np.dot(arr1, arr2)
time_arr_dot = time.time() - start
print(f'Dot Product -> List: {time_list_dot:.5f}s, NumPy: {time_arr_dot:.5f}s')

matrix_size = 1000
mat_list1 = [[random.random() for _ in range(matrix_size)] for _ in range(matrix_size)]
mat_list2 = [[random.random() for _ in range(matrix_size)] for _ in range(matrix_size)]
mat_arr1 = np.array(mat_list1)
mat_arr2 = np.array(mat_list2)

start = time.time()
time_mat_list = time.time() - start

start = time.time()
res_mat_arr = np.dot(mat_arr1, mat_arr2)
time_mat_arr = time.time() - start
print(f'Matrix Mult -> NumPy: {time_mat_arr:.5f}s (List logic skipped for speed as it can take a while)')

Addition -> List: 0.12802s, NumPy: 0.00615s
Multiplication -> List: 0.11639s, NumPy: 0.00643s
Dot Product -> List: 0.08669s, NumPy: 0.00232s
Matrix Mult -> NumPy: 0.07659s (List logic skipped for speed as it can take a while)
